feat(mac.yml): 优化 macOS 构建工作流
- 添加了限制目标目录大小的步骤，确保目录大小不超过 100MB。
- 移动了设置 Node 和 Python 版本的步骤顺序，以提高逻辑清晰度。
- 增加了根据标签前缀确定发布渠道和版本的步骤。
- 添加了草拟发布说明的步骤，并在发布通道为 preview 或 stable 时创建草稿发布。
- 修改了构建 macOS 应用包的步骤，增加了重命名二进制文件的逻辑。
- 添加了根据主分支或特定标签上传应用包的步骤，分别上传 aarch64 和 x86_64 的应用包。
- 更新了上传应用包到 GitHub 发布的步骤，使用 `softprops/action-gh-release`，并根据发布渠道设置 draft 和 prerelease 标志。

diff --git a/.github/workflows/mac.yml b/.github/workflows/mac.yml
--- a/.github/workflows/mac.yml
+++ b/.github/workflows/mac.yml
@@ -21,16 +21,15 @@ jobs:
       CARGO_INCREMENTAL: 0
       RUST_BACKTRACE: 1
     steps:
-      - name: Install Node
-        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
-        with:
-          node-version: "18"
-
       - name: 设置 Python 3.10
         uses: actions/setup-python@v3
         with:
           python-version: "3.10"
-      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
+
+      - name: Install Node
+        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
+        with:
+          node-version: "18"
 
       - name: 手动同步 zed 源代码
         uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
@@ -39,25 +38,59 @@ jobs:
           ref:  main
           path: zed
 
-      - name: Set release channel to nightly
+      - name: Limit target directory size
+        run: cd zed && script/clear-target-dir-if-larger-than 100
+
+      - name: Determine version and release channel
+        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
         run: |
-          cd zed
-          set -eu
-          version=$(git rev-parse --short HEAD)
-          echo "Publishing version: ${version} on release channel nightly"
-          echo "nightly" > crates/zed/RELEASE_CHANNEL
+          # This exports RELEASE_CHANNEL into env (GITHUB_ENV)
+          cd zed && script/determine-release-channel
 
+      - name: Draft release notes
+        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
+        run: |
+          cd zed && mkdir -p target/
+          # Ignore any errors that occur while drafting release notes to not fail the build.
+          script/draft-release-notes "$RELEASE_VERSION" "$RELEASE_CHANNEL" > target/release-notes.md || true
+          script/create-draft-release target/release-notes.md
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: 编译
+      - name: Create macOS app bundle
         run: python3 replace.py && cd zed && script/bundle-mac
 
-      - name: 移动文件
-        run: move macos
+      - name: Rename binaries
+        if: ${{ github.ref == 'refs/heads/main' }} || contains(github.event.pull_request.labels.*.name, 'run-bundling') }}
+        run: |
+          cd zed
+          mv target/aarch64-apple-darwin/release/Zed.dmg target/aarch64-apple-darwin/release/Zed-aarch64.dmg
+          mv target/x86_64-apple-darwin/release/Zed.dmg target/x86_64-apple-darwin/release/Zed-x86_64.dmg
 
-      - name: 上传
-        uses: actions/upload-artifact@v4
+      - name: Upload app bundle (aarch64) to workflow run if main branch or specific label
+        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
+        if: ${{ github.ref == 'refs/heads/main' }} || contains(github.event.pull_request.labels.*.name, 'run-bundling') }}
         with:
-          path: |
-            Zed-aarch64.dmg
-            Zed-x86_64.dmg
-            zed-remote-server-*.gz
+          name: Zed_${{ github.event.pull_request.head.sha || github.sha }}-aarch64.dmg
+          path: zed/target/aarch64-apple-darwin/release/Zed-aarch64.dmg
+
+      - name: Upload app bundle (x86_64) to workflow run if main branch or specific label
+        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
+        if: ${{ github.ref == 'refs/heads/main' }} || contains(github.event.pull_request.labels.*.name, 'run-bundling') }}
+        with:
+          name: Zed_${{ github.event.pull_request.head.sha || github.sha }}-x86_64.dmg
+          path: zed/target/x86_64-apple-darwin/release/Zed-x86_64.dmg
+
+      - uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v1
+        name: Upload app bundle to release
+        if: ${{ env.RELEASE_CHANNEL == 'preview' || env.RELEASE_CHANNEL == 'stable' }}
+        with:
+          draft: true
+          prerelease: ${{ env.RELEASE_CHANNEL == 'preview' }}
+          files: |
+            zed/target/zed-remote-server-macos-x86_64.gz
+            zed/target/zed-remote-server-macos-aarch64.gz
+            zed/target/aarch64-apple-darwin/release/Zed-aarch64.dmg
+            zed/target/x86_64-apple-darwin/release/Zed-x86_64.dmg
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
